"""initial

Revision ID: ee81ecf8448d
Revises: 
Create Date: 2026-05-24 23:51:43.147147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee81ecf8448d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('should_go_outside', sa.Boolean(), nullable=True),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind')
    op.drop_table('weather')
    # ### end Alembic commands ###
